package:
  name: perl-role-tiny
  version: "2.000007"

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Role-Tiny-2.000007.tar.gz
  sha256: 33af02d79d5e9ae76172fd1b2a80230bd8cfde146e1b9327a094a6dfdec6fb56

build:
  number: 0

requirements:
  host:
    - perl
    - perl-exporter

  run:
    - perl
    - perl-exporter
    
test:
  # Perl 'use' tests
  imports:
    - Role::Tiny
    - Role::Tiny::With

about:
  home: http://metacpan.org/pod/Role-Tiny
  license: perl_5
  summary: 'Roles. Like a nouvelle cuisine portion size slice of Moose.'
